config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'

  resources :entries

  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    
    def index
        @entries = Entry.all
    end

    def show
        @entry = Entry.find(params[:id])
    end

    def new
    end

    def create
        @entry = Entry.new(entry_params)

        @entry.save
        redirect_to @entry
    end


    private
        def entry_params
            params.require(:entry).permit(:content)
        end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/entries/index.html.erb
<h1>W R I T E S T U F F</h1>

<table>
    <tr>
        <th>Date Added</th>
    </tr>

    <% @entries.each do |entry| %>
        <tr>
            <td><%= entry.created_at %></td>
            <td><%= link_to 'Show', entry_path(entry) %></td>
        </tr>
    <% end %>
</table>

app/views/entries/new.html.erb
<%= form_with scope: :entry, url: entries_path, local: true do |form| %>

    <!--
    <p>
        <%= form.label :prompt %><br>
        <%= form.text_field :prompt%><br>
    </p>
    -->

    <p>
        <h2>Now type the WRITE STUFF</h2>
        <%= form.text_area :content%><br>
    </p>

    <p>
        <div>
        Word count: <div id="count"></div>
        </div>
    </p>

    <script>

        document.getElementsByTagName("textarea")[0].addEventListener("keyup",  updateWordCount);

        function updateWordCount()
        {
            text = document.getElementsByTagName("textarea")[0];
            wordcount = wordCount(text.value);
            wordcount_elem = document.getElementById("count");
            wordcount_elem.innerHTML = wordcount;
            
            // if (wordcount >= 10)
            // {
            //     alert("Wow good job");
            // }  
        }

        function wordCount(text)
        {
            words = text.split(" ");
            return words.length;
        }
    
    </script>

    <p>
        <%= form.submit %>
    </p>

<% end %>

app/views/entries/show.html.erb
<!--
<p>
    <strong>Prompt:</strong>
    <%= @entry.prompt %>
</p>
-->

<p>
    <strong>Content:</strong>
    <%= @entry.content %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Writestuff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>